Vagrant.configure("2") do |config|
  config.vm.box = "fedora/38-cloud-base"

  config.vm.define "firebotdemo-vm" do |vm|
  config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 4
      libvirt.memory = 8192
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "/firebotdemo/ansible/setup_vm.yml"
    
    end
  end
end

  # Networking
 # config.vm.network "private_network", type: "dhcp"

 # config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "setup.yml"
 # end 	
  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "setup_provisions.yml"

#  config.vm.provision "shell", path: "start_react.sh"
 # config.vm.provision "shell", path: "start_django.sh"
 # end
 # config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "setup_models.yml"
 # end

#end
